<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Google.Protobuf" Version="3.36.2" />
      <PackageReference Include="Grpc.AspNetCore" Version="2.84.0" />
      <PackageReference Include="Grpc.Net.Client" Version="2.84.0" />
      <PackageReference Include="Grpc.Tools" Version="2.84.0">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="IndependentReserve.Grpc.Tools" Version="4.3.257">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Serilog.AspNetCore" Version="10.0.1-dev-02312" />
      <PackageReference Include="Serilog.Settings.Configuration" Version="10.0.1" />
      <PackageReference Include="Serilog.Sinks.File" Version="8.0.0-nblumhardt-02322" />
    </ItemGroup>

    <ItemGroup>
      <Protobuf Include="Protos\message.proto">
        <GrpcServices>Client</GrpcServices>
        <Access>Public</Access>
        <ProtoCompile>True</ProtoCompile>
        <CompileOutputs>True</CompileOutputs>
        <OutputDir>obj\Debug/net10.0/</OutputDir>
        <Generator>MSBuild:Compile</Generator>
      </Protobuf>
    </ItemGroup>

</Project>
