using Grpc.Net.Client;
using GrpcServices;

// Create a channel targeting the server's address
using var channel = GrpcChannel.ForAddress("http://localhost:5000");

// The client is auto-generated by the gRPC tooling from the .proto file
var client = new MessageService.MessageServiceClient(channel);

Console.WriteLine("--- 1. Fetching Initial Messages (RPC 'GET') ---");
var initialMessages = await client.GetMessagesAsync(new Empty());
foreach (var item in initialMessages.Items)
{
    Console.WriteLine($"Message: {item.Message}");
}

Console.WriteLine("\n--- Enter a new message to the list:");
var newMessage = Console.ReadLine();
var response = await client.AddMessageAsync(new MessageRequest { Message = newMessage });
Console.WriteLine($"Success! Added message: {response.Message}");

Console.WriteLine("\n--- 3. Fetching Updated Items ---");
var updatedItems = await client.GetMessagesAsync(new Empty());
foreach (var item in updatedItems.Items)
{
    Console.WriteLine($"{item.Message}");
}