using Grpc.Net.Client;
using GrpcServices;

// Create a channel targeting the server's address
using var channel = GrpcChannel.ForAddress("http://master-service:5003");

// The client is auto-generated by the gRPC tooling from the .proto file
var client = new MessageService.MessageServiceClient(channel);

Console.WriteLine(" Console application started.");
Console.WriteLine(" Type 'exit' to close the program.");
Console.WriteLine("Fetching initial messages:");
var initialMessages = await client.GetMessagesAsync(new Empty());
foreach (var item in initialMessages.Items)
{
    Console.WriteLine($"Message: {item.Message}");
}

while(true)
{
    Console.WriteLine("Enter a new message to the list:");
   
    var newMessage = Console.ReadLine();
    if (string.Equals(newMessage?.Trim(), "exit", StringComparison.OrdinalIgnoreCase))
    {
        Console.WriteLine("Exiting console application...");
        break;
    }
    
    var response = await client.AddMessageAsync(new MessageRequest { Message = newMessage });
    Console.WriteLine($"Success! Added message: {response.Message}");
    Console.WriteLine("Fetching updated messages:");
    var updatedItems = await client.GetMessagesAsync(new Empty());
    foreach (var item in updatedItems.Items)
    {
        Console.WriteLine($"{item.Message}");
    }
}